### ISSUE TITLE
Soulfork entity ticking when thrown

### ISSUE THREAD

**Issue by Hir0shiyt** [Ladysnake/Impaled#61]
Impaled 1.1.4
Fabric loader 1.16.2
Minecraft 1.19.2
When throwing the trident at an entity the gmae crashes.

Log:

````
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-08-24 14:15:02
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "id" is null
	at io.github.apace100.apoli.power.ReplaceLootTablePower.hasReplacement(ReplaceLootTablePower.java:58)
	at net.minecraft.class_52.md992576$apoli$lambda$modifyLootTable$0$1(class_52.java:1078)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at net.minecraft.class_52.handler$zcg000$apoli$modifyLootTable(class_52.java:1080)
	at net.minecraft.class_52.method_328(class_52.java)
	at net.minecraft.class_52.method_320(class_52.java:83)
	at net.minecraft.class_1309.method_16077(class_1309.java:1421)
	at net.minecraft.class_1308.method_16077(class_1308.java:514)
	at net.minecraft.class_1309.method_16080(class_1309.java:1392)
	at net.minecraft.class_1309.method_6078(class_1309.java:1348)
	at net.minecraft.class_1308.method_6078(class_1308.java:3133)
	at net.minecraft.class_3763.method_6078(class_3763.java:178)
	at net.minecraft.class_1309.method_5643(class_1309.java:1204)
	at net.minecraft.class_3763.method_5643(class_3763.java:295)
	at net.minecraft.class_1685.method_7454(class_1685.java:138)
	at net.minecraft.class_1676.method_7488(class_1676.java:149)
	at net.minecraft.class_1665.method_5773(class_1665.java:226)
	at net.minecraft.class_1685.method_5773(class_1685.java:90)
	at ladysnake.impaled.common.entity.SoulforkEntity.method_5773(SoulforkEntity.java:31)
	at net.minecraft.class_3218.track(class_3218.java:12743)
	at net.minecraft.class_3218.redirect$fdj000$observable$onTickNonPassenger(class_3218.java:12759)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.apoli.power.ReplaceLootTablePower.hasReplacement(ReplaceLootTablePower.java:58)
	at net.minecraft.class_52.md992576$apoli$lambda$modifyLootTable$0$1(class_52.java:1078)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at net.minecraft.class_52.handler$zcg000$apoli$modifyLootTable(class_52.java:1080)
	at net.minecraft.class_52.method_328(class_52.java)
	at net.minecraft.class_52.method_320(class_52.java:83)
	at net.minecraft.class_1309.method_16077(class_1309.java:1421)
	at net.minecraft.class_1308.method_16077(class_1308.java:514)
	at net.minecraft.class_1309.method_16080(class_1309.java:1392)
	at net.minecraft.class_1309.method_6078(class_1309.java:1348)
	at net.minecraft.class_1308.method_6078(class_1308.java:3133)
	at net.minecraft.class_3763.method_6078(class_3763.java:178)
	at net.minecraft.class_1309.method_5643(class_1309.java:1204)
	at net.minecraft.class_3763.method_5643(class_3763.java:295)
	at net.minecraft.class_1685.method_7454(class_1685.java:138)
	at net.minecraft.class_1676.method_7488(class_1676.java:149)
	at net.minecraft.class_1665.method_5773(class_1665.java:226)
	at net.minecraft.class_1685.method_5773(class_1685.java:90)
	at ladysnake.impaled.common.entity.SoulforkEntity.method_5773(SoulforkEntity.java:31)
	at net.minecraft.class_3218.track(class_3218.java:12743)
	at net.minecraft.class_3218.redirect$fdj000$observable$onTickNonPassenger(class_3218.java:12759)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: impaled:soulfork (ladysnake.impaled.common.entity.SoulforkEntity)
	Entity ID: 916
	Entity Name: entity.impaled.soulfork
	Entity's Exact location: 10867.45, 70.52, -2971.47
	Entity's Block location: World: (10867,70,-2972), Section: (at 3,6,4 in 679,4,-186; chunk contains blocks 10864,-64,-2976 to 10879,319,-2961), Region: (21,-6; contains chunks 672,-192 to 703,-161, blocks 10752,-64,-3072 to 11263,319,-2561)
	Entity's Momentum: -1.09, -1.48, 1.66
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)
````

**Comment by ninjaguardian** [comment]
This may be due to an incompatibility with origins.
