### ISSUE TITLE
Client crashes if removed from server after throwing trident

### ISSUE THREAD

**Issue by williambl** [Ladysnake/Impaled#62]
I'm not entirely sure of the steps to reproduce here but I think it was:
- I threw a trident
- It landed
- Server crashed/kicked me for unrelated reasons before the trident made its way back to my hand
- After about half a second of the disconnected screen, I get a 'Saving World...' screen, then my client crashes

version: 1.1.5 for mc 1.19.2

stacktrace:
```
java.lang.IllegalStateException: Cannot send packets when not in game!
	at org.quiltmc.qsl.networking.api.client.ClientPlayNetworking.send(ClientPlayNetworking.java:228)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking.send(ClientPlayNetworking.java:204)
	at ladysnake.sincereloyalty.SincereLoyaltyClient.lambda$onInitializeClient$0(SincereLoyaltyClient.java:51)
	at org.quiltmc.qsl.lifecycle.api.client.event.ClientTickEvents.lambda$static$2(ClientTickEvents.java:54)
	at net.minecraft.class_310.handler$chk001$quilt_lifecycle_events$endTick(class_310.java:10505)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by ninjaguardian** [comment]
I don't see a 1.1.5 for Impaled... Also can you send more info besides just the error? For example, the mods you use.

**Comment by Kirame1717** [comment]
Was the 1.1.5 version just wiped from the archives? I can't find any links to it anywhere and the 1.2 version doesn't support 1.20..
